spring:
  config:
    import: optional:file:.env[.properties]

  cloud:
    aws:
      parameterstore:
        enabled: false
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}